# Generated by Django 5.0.3 on 2024-03-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Createuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
                ("passw", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=122)),
                ("Severity", models.CharField(max_length=122)),
                ("priority", models.CharField(max_length=122)),
                ("Assign", models.CharField(max_length=122)),
                ("Summary", models.TextField()),
                ("Desc", models.TextField()),
                ("date", models.DateField()),
                ("Image", models.ImageField(upload_to=None)),
                ("Viewstatus", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pname", models.CharField(max_length=122)),
                ("Pstatus", models.CharField(max_length=122)),
                ("Viewstatus", models.CharField(max_length=50)),
                ("Desc", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
