# Generated by Django 5.0.3 on 2024-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_project_viewstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Project", models.CharField(max_length=122)),
                ("Severity", models.CharField(max_length=122)),
                ("Priority", models.CharField(max_length=122)),
                ("Assign", models.CharField(max_length=122)),
                ("Summary", models.TextField()),
                ("Desc", models.TextField()),
                ("date", models.DateField()),
                ("Image", models.ImageField(upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name="Issue",
        ),
    ]
