# Generated by Django 5.0.3 on 2024-03-16 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_bug_delete_issue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bug",
            old_name="Project",
            new_name="project",
        ),
    ]
