# Generated by Django 5.0.3 on 2024-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_rename_project_bug_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="project",
            field=models.CharField(max_length=122, null=True),
        ),
    ]
