# Generated by Django 5.0.3 on 2024-03-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_bug_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="Severity",
            field=models.CharField(max_length=122, null=True),
        ),
    ]
