# Generated by Django 5.0.3 on 2024-03-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_bug_assign_alter_bug_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="Desc",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="bug",
            name="Summary",
            field=models.TextField(null=True),
        ),
    ]
