# Generated by Django 5.0.3 on 2024-03-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_bug_desc_alter_bug_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="status",
            field=models.CharField(default="Unresolved", max_length=50),
        ),
    ]
