# Generated by Django 5.0.3 on 2024-03-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_remove_bug_date_bug_created_bug_ended_bug_timetaken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bug",
            name="created",
        ),
        migrations.RemoveField(
            model_name="bug",
            name="ended",
        ),
        migrations.RemoveField(
            model_name="bug",
            name="timetaken",
        ),
        migrations.AddField(
            model_name="bug",
            name="date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
