# Generated by Django 5.0.3 on 2024-03-21 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_remove_bug_created_remove_bug_ended_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 3, 21, 11, 21, 32, 728061, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bug",
            name="ended",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bug",
            name="timetaken",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
