# Generated by Django 5.0.3 on 2024-03-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_bug_created_bug_ended_bug_timetaken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="timetaken",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
