# Generated by Django 5.0.3 on 2024-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_bug_timetaken"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="reportedby",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bug",
            name="resolvedby",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
