# Generated by Django 5.0.3 on 2024-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_bug_reportedby_bug_resolvedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="resolvedby",
            field=models.CharField(max_length=100),
        ),
    ]
