# Generated by Django 5.0.3 on 2024-03-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_alter_bug_resolvedby"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="time",
            field=models.DateField(blank=True, null=True),
        ),
    ]
