# Generated by Django 5.0.3 on 2024-03-21 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_bug_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bug",
            name="time",
        ),
    ]
