# Generated by Django 5.0.3 on 2024-04-13 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createuser",
            name="designation",
        ),
    ]
