# Generated by Django 5.0.3 on 2024-04-13 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_userprofile_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
