# Generated by Django 5.0.3 on 2024-04-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_project_users_alter_profile_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="Image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
